---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: BMCCluster
    name: "${CLUSTER_NAME}"
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "${CLUSTER_NAME}-control-plane"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: BMCCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  location: "${BMC_LOCATION}"
  vipManager: "${VIP_MANAGER}"
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  machineTemplate:
    infrastructureRef:
      kind: BMCMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: "${CLUSTER_NAME}-control-plane"
  kubeadmConfigSpec:
    preKubeadmCommands:
    - echo "preKubeadmCommands run"
    - sudo apt-get -y update && sudo apt-get -y install curl
    - wget https://github.com/containerd/containerd/releases/download/v${CONTAINERD_VERSION}/containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
    - tar Cxzvf /usr/local containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
    - rm containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
    - wget -P /etc/systemd/system https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    - systemctl daemon-reload
    - systemctl enable --now containerd
    - wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v${CRI_VERSION}/crictl-v${CRI_VERSION}-linux-amd64.tar.gz
    - sudo tar zxvf crictl-v${CRI_VERSION}-linux-amd64.tar.gz -C /usr/local/bin
    - rm -f crictl-v${CRI_VERSION}-linux-amd64.tar.gz
    - wget https://github.com/opencontainers/runc/releases/download/v${RUNC_VERSION}/runc.amd64
    - install -m 755 runc.amd64 /usr/local/sbin/runc
    - mkdir -p /opt/cni/bin
    - wget https://github.com/containernetworking/plugins/releases/download/v${CNI_VERSION}/cni-plugins-linux-amd64-v${CNI_VERSION}.tgz
    - tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v${CNI_VERSION}.tgz
    - rm cni-plugins-linux-amd64-v${CNI_VERSION}.tgz
    - sudo apt-get -y update
    - modprobe overlay
    - modprobe br_netfilter
    - echo -e "overlay \nbr_netfilter" | sudo tee /etc/modules-load.d/kubernetes.conf
    - mkdir -p /proc/sys/net/bridge
    - echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables /proc/sys/net/bridge/bridge-nf-call-ip6tables /proc/sys/net/ipv4/ip_forward /proc/sys/net/ipv6/conf/all/forwarding /proc/sys/vm/overcommit_memory /proc/sys/kernel/panic_on_oops /proc/sys/net/ipv4/conf/all/rp_filter
    - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
    - echo 10 | sudo tee /proc/sys/kernel/panic
    - curl -fsSL https://pkgs.k8s.io/core:/stable:/$(echo ${KUBERNETES_VERSION} | cut -d'.' -f1,2)/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$(echo ${KUBERNETES_VERSION} | cut -d'.' -f1,2)/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - sudo apt-get -y update
    - sudo apt-get install -y kubelet kubeadm kubectl
    - sudo apt-get -y update
    - sudo swapoff -a
    - sudo mkdir /etc/containerd
    - sudo containerd config default | sudo tee /etc/containerd/config.toml
    - sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    - service containerd restart
    - service kubelet restart
    - echo "preKubeadmCommands finished"
    - "echo 'Updating kube-vip config with controlPlaneEndpoint IP...'"
    - |
      if [ -f /run/kubeadm/kubeadm.yaml ]; then
        sed -i "s/PLACEHOLDER/$(grep controlPlaneEndpoint /run/kubeadm/kubeadm.yaml | awk '{print $2}' | tr -d '\"' | cut -d':' -f1)/" /etc/kubernetes/manifests/kube-vip.yaml
      else
        sed -i "s/PLACEHOLDER/$(grep apiServerEndpoint /run/kubeadm/kubeadm-join-config.yaml | awk '{print $2}' | tr -d '\"' | cut -d':' -f1)/" /etc/kubernetes/manifests/kube-vip.yaml
      fi
    files:
    - content: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: kube-vip
          namespace: kube-system
        spec:
          containers:
            - args:
                - manager
              env:
                - name: vip_arp
                  value: "false"
                - name: port
                  value: "6443"
                - name: vip_cidr
                  value: "32"
                - name: cp_enable
                  value: "true"
                - name: cp_namespace
                  value: kube-system
                - name: vip_ddns
                  value: "false"
                - name: bgp_enable
                  value: "true"
                - name: bgp_routerid
                  value: 169.254.247.0
                - name: bgp_as
                  value: "65401"
                - name: bgp_peeraddress
                  value: 169.254.247.0
                - name: bgp_peerpass
                  value: "${BGP_PEERPASS}"
                - name: bgp_peeras
                  value: "65400"
                - name: address
                  value: PLACEHOLDER
                - name: bgp_multihop
                  value: "true"
              image: ghcr.io/kube-vip/kube-vip:v0.8.9
              imagePullPolicy: Always
              name: kube-vip
              resources: {}
              securityContext:
                capabilities:
                  add:
                    - NET_ADMIN
                    - NET_RAW
                    - SYS_TIME
              volumeMounts:
                - mountPath: /etc/kubernetes/admin.conf
                  name: kubeconfig
          hostAliases:
          - hostnames:
            - kubernetes
            ip: 127.0.0.1
          hostNetwork: true
          volumes:
            - hostPath:
                path: /etc/kubernetes/admin.conf
              name: kubeconfig
        status: {}
      owner: root:root
      path: /etc/kubernetes/manifests/kube-vip.yaml
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
  version: "${KUBERNETES_VERSION}"
---
kind: BMCMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      location: "${BMC_LOCATION}"
      os: "ubuntu/jammy"
      type: "${BMC_CONTROL_PLANE_MACHINE_TYPE}"
      installDefaultSshKeys: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "${CLUSTER_NAME}-wmd"
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "${CLUSTER_NAME}"
      version: "${KUBERNETES_VERSION}"
      bootstrap:
        configRef:
          name: "${CLUSTER_NAME}-kcfg-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: "${CLUSTER_NAME}-mt-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: BMCMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: BMCMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-mt-0"
spec:
  template:
    spec:
      location: "${BMC_LOCATION}"
      os: "ubuntu/jammy"
      type: "${BMC_NODE_TYPE}"
      installDefaultSshKeys: true
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-kcfg-0"
spec:
  template:
    spec:
      preKubeadmCommands:
      - echo "preKubeadmCommands run"
      - sudo apt-get -y update && sudo apt-get -y install curl
      - wget https://github.com/containerd/containerd/releases/download/v${CONTAINERD_VERSION}/containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
      - tar Cxzvf /usr/local containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
      - rm containerd-${CONTAINERD_VERSION}-linux-amd64.tar.gz
      - wget -P /etc/systemd/system https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
      - systemctl daemon-reload
      - systemctl enable --now containerd
      - wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v${CRI_VERSION}/crictl-v${CRI_VERSION}-linux-amd64.tar.gz
      - sudo tar zxvf crictl-v${CRI_VERSION}-linux-amd64.tar.gz -C /usr/local/bin
      - rm -f crictl-v${CRI_VERSION}-linux-amd64.tar.gz
      - wget https://github.com/opencontainers/runc/releases/download/v${RUNC_VERSION}/runc.amd64
      - install -m 755 runc.amd64 /usr/local/sbin/runc
      - mkdir -p /opt/cni/bin
      - wget https://github.com/containernetworking/plugins/releases/download/v${CNI_VERSION}/cni-plugins-linux-amd64-v${CNI_VERSION}.tgz
      - tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v${CNI_VERSION}.tgz
      - rm cni-plugins-linux-amd64-v${CNI_VERSION}.tgz
      - sudo apt-get -y update
      - modprobe overlay
      - modprobe br_netfilter
      - echo -e "overlay \nbr_netfilter" | sudo tee /etc/modules-load.d/kubernetes.conf
      - mkdir -p /proc/sys/net/bridge
      - echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables /proc/sys/net/bridge/bridge-nf-call-ip6tables /proc/sys/net/ipv4/ip_forward /proc/sys/net/ipv6/conf/all/forwarding /proc/sys/vm/overcommit_memory /proc/sys/kernel/panic_on_oops /proc/sys/net/ipv4/conf/all/rp_filter
      - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
      - echo 10 | sudo tee /proc/sys/kernel/panic
      - curl -fsSL https://pkgs.k8s.io/core:/stable:/$(echo ${KUBERNETES_VERSION} | cut -d'.' -f1,2)/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$(echo ${KUBERNETES_VERSION} | cut -d'.' -f1,2)/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      - sudo apt-get -y update
      - sudo apt-get install -y kubelet kubeadm kubectl
      - sudo apt-get -y update
      - sudo swapoff -a
      - sudo mkdir /etc/containerd
      - sudo containerd config default | sudo tee /etc/containerd/config.toml
      - sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      - service containerd restart
      - service kubelet restart
      - echo "preKubeadmCommands finished"
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.local_hostname }}'
